package hooks

import (
	"testing"
	"testing/fstest"
)

func TestDetectRunner(t *testing.T) {
	tests := []struct {
		name     string
		hookFile string
		content  string
		want     Runner
		wantOK   bool
	}{
		{"lefthook", ".git/hooks/pre-push", "#!/bin/sh\ncall_lefthook run \"pre-push\" \"$@\"\n", RunnerLefthook, true},
		{"husky はパスで判定する", "/repo/.husky/_/pre-push", ". \"$(dirname \"$0\")/h\"\n", RunnerHusky, true},
		{"pre-commit", ".git/hooks/commit-msg", "# File generated by pre-commit: https://pre-commit.com\n", RunnerPreCommit, true},
		{"未知のフック", ".git/hooks/pre-push", "echo hi\n", "", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := DetectRunner(tt.hookFile, tt.content)
			if got != tt.want || ok != tt.wantOK {
				t.Errorf("DetectRunner() = (%q, %v), want (%q, %v)", got, ok, tt.want, tt.wantOK)
			}
		})
	}
}

func TestInspectRunnerConfig(t *testing.T) {
	tests := []struct {
		name         string
		files        map[string]string
		runner       Runner
		hook         Hook
		wantFound    bool
		wantLocation string
		wantProblem  bool
	}{
		{
			name:   "lefthook commit-msg",
			files:  map[string]string{"lefthook.yml": "commit-msg:\n  commands:\n    spotter:\n      run: spotter check --message {1}\n"},
			runner: RunnerLefthook, hook: HookCommitMsg,
			wantFound: true, wantLocation: "lefthook.yml: commit-msg.commands.spotter",
		},
		{
			name:   "lefthook pre-push で use_stdin あり",
			files:  map[string]string{".lefthook.yaml": "pre-push:\n  commands:\n    spotter:\n      run: spotter check --pre-push {1}\n      use_stdin: true\n"},
			runner: RunnerLefthook, hook: HookPrePush,
			wantFound: true, wantLocation: ".lefthook.yaml: pre-push.commands.spotter",
		},
		{
			name:   "lefthook pre-push で use_stdin の付け忘れ",
			files:  map[string]string{"lefthook.yml": "pre-push:\n  commands:\n    spotter:\n      run: spotter check --pre-push {1}\n"},
			runner: RunnerLefthook, hook: HookPrePush,
			wantFound: true, wantLocation: "lefthook.yml: pre-push.commands.spotter", wantProblem: true,
		},
		{
			name: "lefthook-local.yml が use_stdin を補う",
			files: map[string]string{
				"lefthook.yml":       "pre-push:\n  commands:\n    spotter:\n      run: spotter check --pre-push {1}\n",
				"lefthook-local.yml": "pre-push:\n  commands:\n    spotter:\n      run: spotter check --pre-push {1}\n      use_stdin: true\n",
			},
			runner: RunnerLefthook, hook: HookPrePush,
			wantFound: true, wantLocation: "lefthook-local.yml: pre-push.commands.spotter",
		},
		{
			name:   "lefthook jobs 形式",
			files:  map[string]string{"lefthook.yml": "pre-push:\n  jobs:\n    - name: spotter\n      run: spotter check --pre-push {1}\n      use_stdin: true\n"},
			runner: RunnerLefthook, hook: HookPrePush,
			wantFound: true, wantLocation: "lefthook.yml: pre-push.jobs.spotter",
		},
		{
			name:   "lefthook 別フックの設定だけ",
			files:  map[string]string{"lefthook.yml": "commit-msg:\n  commands:\n    spotter:\n      run: spotter check --message {1}\n"},
			runner: RunnerLefthook, hook: HookPrePush,
		},
		{
			name:   "lefthook 設定ファイル無し",
			files:  map[string]string{},
			runner: RunnerLefthook, hook: HookPrePush,
		},
		{
			name:   "husky あり",
			files:  map[string]string{".husky/pre-push": "spotter check --pre-push \"$1\"\n"},
			runner: RunnerHusky, hook: HookPrePush,
			wantFound: true, wantLocation: ".husky/pre-push",
		},
		{
			name:   "husky に spotter が無い",
			files:  map[string]string{".husky/pre-push": "npm test\n"},
			runner: RunnerHusky, hook: HookPrePush,
		},
		{
			name:   "pre-commit で stage 一致",
			files:  map[string]string{".pre-commit-config.yaml": "repos:\n  - repo: local\n    hooks:\n      - id: spotter-commit-msg\n        entry: spotter check --message\n        stages: [commit-msg]\n"},
			runner: RunnerPreCommit, hook: HookCommitMsg,
			wantFound: true, wantLocation: ".pre-commit-config.yaml: spotter-commit-msg",
		},
		{
			name:   "pre-commit で旧名 push の stage",
			files:  map[string]string{".pre-commit-config.yaml": "repos:\n  - repo: local\n    hooks:\n      - id: sp\n        entry: spotter check --pre-push x\n        stages: [push]\n"},
			runner: RunnerPreCommit, hook: HookPrePush,
			wantFound: true, wantLocation: ".pre-commit-config.yaml: sp",
		},
		{
			name:   "pre-commit で stage 不一致",
			files:  map[string]string{".pre-commit-config.yaml": "repos:\n  - repo: local\n    hooks:\n      - id: sp\n        entry: spotter check --message\n        stages: [commit-msg]\n"},
			runner: RunnerPreCommit, hook: HookPrePush,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fsys := fstest.MapFS{}
			for name, content := range tt.files {
				fsys[name] = &fstest.MapFile{Data: []byte(content)}
			}
			got, err := InspectRunnerConfig(fsys, tt.runner, tt.hook)
			if err != nil {
				t.Fatalf("InspectRunnerConfig: %v", err)
			}
			if got.Found != tt.wantFound || got.Location != tt.wantLocation || (got.Problem != "") != tt.wantProblem {
				t.Errorf("InspectRunnerConfig() = %+v", got)
			}
		})
	}
}

func TestInspectRunnerConfigErrors(t *testing.T) {
	if _, err := InspectRunnerConfig(fstest.MapFS{}, Runner("x"), HookPrePush); err == nil {
		t.Error("未知のランナーでエラーにならなかった")
	}
	bad := fstest.MapFS{
		"lefthook.yml":            {Data: []byte("a: [\n")},
		".pre-commit-config.yaml": {Data: []byte("a: [\n")},
	}
	for _, r := range []Runner{RunnerLefthook, RunnerPreCommit} {
		if _, err := InspectRunnerConfig(bad, r, HookPrePush); err == nil {
			t.Errorf("%s: 不正な YAML でエラーにならなかった", r)
		}
	}
}
