// Package commitintent はコミットメッセージの type/scope と、実際の変更内容（差分）の
// 整合を検査する。commit-subject が subject の体裁だけを見るのに対し、こちらは
// 「docs: と名乗りながらコードを書き換えている」のような、申告と実態の乖離を検知する。
package commitintent

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/bmatcuk/doublestar/v4"

	"github.com/fuchigta/spotter/internal/check"
	"github.com/fuchigta/spotter/internal/check/diffutil"
	"github.com/fuchigta/spotter/internal/commitmsg"
	"github.com/fuchigta/spotter/internal/config"
)

const (
	onAdded   = "added"
	onRemoved = "removed"
)

type rule struct {
	types      []string
	typesSet   map[string]bool
	scopesSet  map[string]bool
	breaking   *bool
	allow      []string
	require    []string
	deny       []string
	denyDiff   *regexp.Regexp
	denyDiffRe string
	on         string
	reason     string
}

func (r rule) label() string {
	return strings.Join(r.types, "/")
}

// Check は commit-intent 検査の 1 インスタンス。
type Check struct {
	rules []rule
}

// New は config.CheckConfig から Check を組み立てる。rules の各項目はここで検証し、
// 不正な設定は起動時に検出する。
func New(cc config.CheckConfig) (*Check, error) {
	if len(cc.Rules) == 0 {
		return nil, fmt.Errorf("commitintent: rules には少なくとも 1 件のルールが必要です")
	}

	c := &Check{}
	for _, rc := range cc.Rules {
		if len(rc.Types) == 0 {
			return nil, fmt.Errorf("commitintent: rules には types が必要です")
		}
		for _, t := range rc.Types {
			if t == "" {
				return nil, fmt.Errorf("commitintent: rules.types に空文字は指定できません")
			}
		}
		if len(rc.Allow) == 0 && len(rc.Require) == 0 && rc.DenyDiff == "" && len(rc.Deny) == 0 {
			return nil, fmt.Errorf("commitintent: rules には allow / require / deny_diff / deny のいずれか 1 つが必要です")
		}

		typesSet := make(map[string]bool, len(rc.Types))
		for _, t := range rc.Types {
			typesSet[t] = true
		}

		var scopesSet map[string]bool
		if len(rc.Scopes) > 0 {
			scopesSet = make(map[string]bool, len(rc.Scopes))
			for _, s := range rc.Scopes {
				if s == "" {
					return nil, fmt.Errorf("commitintent: rules.scopes に空文字は指定できません")
				}
				scopesSet[s] = true
			}
		}

		for _, p := range rc.Allow {
			if !doublestar.ValidatePattern(p) {
				return nil, fmt.Errorf("commitintent: rules.allow: パターン %q が不正です", p)
			}
		}
		for _, p := range rc.Require {
			if !doublestar.ValidatePattern(p) {
				return nil, fmt.Errorf("commitintent: rules.require: パターン %q が不正です", p)
			}
		}
		for _, p := range rc.Deny {
			if !doublestar.ValidatePattern(p) {
				return nil, fmt.Errorf("commitintent: rules.deny: パターン %q が不正です", p)
			}
		}
		if rc.On != "" {
			if rc.DenyDiff == "" {
				return nil, fmt.Errorf("commitintent: rules.on は deny_diff 指定時のみ有効です")
			}
			if rc.On != onAdded && rc.On != onRemoved {
				return nil, fmt.Errorf("commitintent: rules.on %q は未対応です（added | removed）", rc.On)
			}
		}

		r := rule{
			types:      rc.Types,
			typesSet:   typesSet,
			scopesSet:  scopesSet,
			breaking:   rc.Breaking,
			allow:      rc.Allow,
			require:    rc.Require,
			deny:       rc.Deny,
			denyDiffRe: rc.DenyDiff,
			on:         rc.On,
			reason:     rc.Reason,
		}

		if rc.DenyDiff != "" {
			// 差分は複数行なので、"^"/"$" が行頭・行末に効くよう (?m) を自動で付与する
			// （docsync の when と同じ仕様）。on 指定時は 1 行ずつ照合するため (?m) は
			// 効かないが、複数行を当てる従来の使い方と正規表現を使い回せるよう付与自体は
			// 変えない（1 行に対する ^/$ の意味は変わらない）。
			re, err := regexp.Compile(`(?m)` + rc.DenyDiff)
			if err != nil {
				return nil, fmt.Errorf("commitintent: rules.deny_diff %q のコンパイルに失敗しました: %w", rc.DenyDiff, err)
			}
			r.denyDiff = re
		}

		c.rules = append(c.rules, r)
	}
	return c, nil
}

// Granularity はコミットごとに 1 回ずつ見る。メッセージと差分が 1:1 で対応していないと
// 意味を持たないため squashed は選べない。checks 側からは上書きできない。
func (c *Check) Granularity() check.Granularity {
	return check.GranularityPerCommit
}

// Run は ctx.Message から type/scope/breaking を取り出し、一致するルールの
// allow/require/deny/deny_diff をそれぞれ ctx.Source の変更内容と突き合わせる。
func (c *Check) Run(ctx check.Context) ([]check.Violation, error) {
	subject := commitmsg.FirstLine(ctx.Message)
	if commitmsg.IsAutoGenerated(subject) {
		return nil, nil
	}

	parsed, ok := commitmsg.Parse(subject)
	if !ok {
		// subject の体裁の検証は commit-subject の責務。ここで重ねて報告しない。
		return nil, nil
	}

	src := ctx.Source
	changed, err := src.ChangedFiles()
	if err != nil {
		return nil, fmt.Errorf("commitintent: 変更ファイルの取得に失敗しました: %w", err)
	}
	deleted, err := src.DeletedFiles()
	if err != nil {
		return nil, fmt.Errorf("commitintent: 削除ファイルの取得に失敗しました: %w", err)
	}
	if len(changed) == 0 && len(deleted) == 0 {
		return nil, nil
	}

	var violations []check.Violation
	for _, r := range c.rules {
		if !r.typesSet[parsed.Type] {
			continue
		}
		if r.scopesSet != nil && !r.scopesSet[parsed.Scope] {
			continue
		}
		if r.breaking != nil && commitmsg.IsBreaking(ctx.Message) != *r.breaking {
			continue
		}

		if len(r.allow) > 0 {
			var outliers []string
			for _, f := range changed {
				matched, err := matchesAny(r.allow, f)
				if err != nil {
					return nil, fmt.Errorf("commitintent: rules.allow の評価に失敗しました: %w", err)
				}
				if !matched {
					outliers = append(outliers, f)
				}
			}
			// 削除も「このルールが許す範囲を外れた変更」に含める。例えば docs: を
			// 名乗ってコードを削除しても、ChangedFiles（ACMR）だけを見ていると
			// 素通りしてしまうため。
			for _, f := range deleted {
				matched, err := matchesAny(r.allow, f)
				if err != nil {
					return nil, fmt.Errorf("commitintent: rules.allow の評価に失敗しました: %w", err)
				}
				if !matched {
					outliers = append(outliers, check.DeletedLabel(f))
				}
			}
			if len(outliers) > 0 {
				reason := r.reason
				if reason == "" {
					reason = fmt.Sprintf("%s は %s だけを変更するはずです", r.label(), strings.Join(r.allow, ", "))
				}
				violations = append(violations, check.Violation{Summary: reason + ":", Files: outliers})
			}
		}

		if len(r.require) > 0 {
			// require は「変更ファイルの少なくとも 1 つ」を求めるルールなので、削除は
			// 満たしたことにしない（意図的）。例えば「テストを消した」コミットで
			// require: ['**/*_test.go'] を、消したテストファイル自身で満たせては
			// 本末転倒なため、changed（ACMR）だけを見る。
			satisfied := false
			for _, f := range changed {
				matched, err := matchesAny(r.require, f)
				if err != nil {
					return nil, fmt.Errorf("commitintent: rules.require の評価に失敗しました: %w", err)
				}
				if matched {
					satisfied = true
					break
				}
			}
			if !satisfied {
				reason := r.reason
				if reason == "" {
					reason = fmt.Sprintf("%s は対応する変更を伴うはずです", r.label())
				}
				// reason を指定していても、何が不足しているか（require のどのパターンに
				// 一致する変更が要るか）が分かるよう、パターンの一覧を必ず添える。
				summary := fmt.Sprintf("%s（次のいずれかに一致する変更が必要: %s）", reason, strings.Join(r.require, ", "))
				violations = append(violations, check.Violation{Summary: summary + ":", Files: changed})
			}
		}

		if len(r.deny) > 0 {
			var hits []string
			for _, f := range changed {
				matched, err := matchesAny(r.deny, f)
				if err != nil {
					return nil, fmt.Errorf("commitintent: rules.deny の評価に失敗しました: %w", err)
				}
				if matched {
					hits = append(hits, f)
				}
			}
			for _, f := range deleted {
				matched, err := matchesAny(r.deny, f)
				if err != nil {
					return nil, fmt.Errorf("commitintent: rules.deny の評価に失敗しました: %w", err)
				}
				if matched {
					hits = append(hits, check.DeletedLabel(f))
				}
			}
			if len(hits) > 0 {
				reason := r.reason
				if reason == "" {
					reason = fmt.Sprintf("%s は %s を変更してはいけません", r.label(), strings.Join(r.deny, ", "))
				}
				violations = append(violations, check.Violation{Summary: reason + ":", Files: hits})
			}
		}

		if r.denyDiff != nil {
			var hits []string
			collectDenyDiffHits := func(files []string, deleted bool) error {
				for _, f := range files {
					diff, err := src.DiffLines(f)
					if err != nil {
						return fmt.Errorf("commitintent: %s の差分取得に失敗しました: %w", f, err)
					}
					if r.on == "" {
						// 省略時は従来どおり差分テキスト全体に当てる（互換維持）。
						if r.denyDiff.MatchString(diff) {
							if deleted {
								hits = append(hits, check.DeletedLabel(f))
							} else {
								hits = append(hits, f)
							}
						}
						continue
					}
					// on 指定時は追加行/削除行それぞれの中身（先頭の +/- を落とし、
					// ヘッダ行も除いたもの）に 1 行ずつ当て、どの行に一致したかが
					// わかるよう diffutil.FormatHit で "path:line: text" 形式にする。
					added, removed := diffutil.ParseLines(diff)
					lines := added
					if r.on == onRemoved {
						lines = removed
					}
					for _, ln := range lines {
						if r.denyDiff.MatchString(ln.Text) {
							hits = append(hits, diffutil.FormatHit(f, ln.Num, ln.Text))
						}
					}
				}
				return nil
			}
			if err := collectDenyDiffHits(changed, false); err != nil {
				return nil, err
			}
			// 削除も差分を持つ（消えた内容が "-" 行として出る）ため、同じ禁止パターンを
			// 削除ファイルの差分にも当てる。「refactor: と称してコードごと消す」のような
			// 抜け穴を防ぐ。
			if err := collectDenyDiffHits(deleted, true); err != nil {
				return nil, err
			}
			if len(hits) > 0 {
				reason := r.reason
				if reason == "" {
					reason = fmt.Sprintf("%s の差分が禁止パターン %s に一致しています", r.label(), r.denyDiffRe)
				}
				violations = append(violations, check.Violation{Summary: reason + ":", Files: hits})
			}
		}
	}

	return violations, nil
}

func matchesAny(patterns []string, f string) (bool, error) {
	for _, pat := range patterns {
		ok, err := doublestar.Match(pat, f)
		if err != nil {
			return false, err
		}
		if ok {
			return true, nil
		}
	}
	return false, nil
}
