// Package commitintent はコミットメッセージの type/scope と、実際の変更内容（差分）の
// 整合を検査する。commit-subject が subject の体裁だけを見るのに対し、こちらは
// 「docs: と名乗りながらコードを書き換えている」のような、申告と実態の乖離を検知する。
package commitintent

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/bmatcuk/doublestar/v4"

	"github.com/fuchigta/spotter/internal/check"
	"github.com/fuchigta/spotter/internal/check/diffutil"
	"github.com/fuchigta/spotter/internal/commitmsg"
	"github.com/fuchigta/spotter/internal/config"
)

type rule struct {
	types      []string
	typesSet   map[string]bool
	scopesSet  map[string]bool
	breaking   *bool
	allow      []string
	require    []string
	deny       []string
	denyDiff   *regexp.Regexp
	denyDiffRe string
	on         string
	reason     string
}

func (r rule) label() string {
	return strings.Join(r.types, "/")
}

// Check は commit-intent 検査の 1 インスタンス。
type Check struct {
	rules []rule
}

// New は rules の各項目を検証してから Check を組み立てる。不正な設定は起動時に検出する。
func New(cc config.CheckConfig) (*Check, error) {
	if len(cc.Rules) == 0 {
		return nil, fmt.Errorf("commitintent: rules には少なくとも 1 件のルールが必要です")
	}

	c := &Check{}
	for _, rc := range cc.Rules {
		if err := validateRuleConfig(rc); err != nil {
			return nil, err
		}
		r, err := buildRule(rc)
		if err != nil {
			return nil, err
		}
		c.rules = append(c.rules, r)
	}
	return c, nil
}

// validateRuleConfig は config.CommitIntentRule の 1 件分を検証する。項目ごとの検証を
// 個別の関数に分け、New 全体の見通しを保つ。
func validateRuleConfig(rc config.CommitIntentRule) error {
	if err := validateTypes(rc.Types); err != nil {
		return err
	}
	if len(rc.Allow) == 0 && len(rc.Require) == 0 && rc.DenyDiff == "" && len(rc.Deny) == 0 {
		return fmt.Errorf("commitintent: rules には allow / require / deny_diff / deny のいずれか 1 つが必要です")
	}
	if err := validateScopes(rc.Scopes); err != nil {
		return err
	}
	if err := validatePatterns("allow", rc.Allow); err != nil {
		return err
	}
	if err := validatePatterns("require", rc.Require); err != nil {
		return err
	}
	if err := validatePatterns("deny", rc.Deny); err != nil {
		return err
	}
	return validateOn(rc)
}

func validateTypes(types []string) error {
	if len(types) == 0 {
		return fmt.Errorf("commitintent: rules には types が必要です")
	}
	for _, t := range types {
		if t == "" {
			return fmt.Errorf("commitintent: rules.types に空文字は指定できません")
		}
	}
	return nil
}

func validateScopes(scopes []string) error {
	for _, s := range scopes {
		if s == "" {
			return fmt.Errorf("commitintent: rules.scopes に空文字は指定できません")
		}
	}
	return nil
}

// validatePatterns は allow/require/deny のいずれかのパターン一覧を検証する。kind は
// エラーメッセージに出すフィールド名（"allow" などそのまま rules.<kind> になる）。
func validatePatterns(kind string, patterns []string) error {
	for _, p := range patterns {
		if !doublestar.ValidatePattern(p) {
			return fmt.Errorf("commitintent: rules.%s: パターン %q が不正です", kind, p)
		}
	}
	return nil
}

func validateOn(rc config.CommitIntentRule) error {
	if rc.On == "" {
		return nil
	}
	if rc.DenyDiff == "" {
		return fmt.Errorf("commitintent: rules.on は deny_diff 指定時のみ有効です")
	}
	if err := diffutil.ValidateOn(rc.On); err != nil {
		return fmt.Errorf("commitintent: rules.on: %w", err)
	}
	return nil
}

// buildRule は検証済みの config.CommitIntentRule から rule を組み立てる。deny_diff の
// 正規表現コンパイルだけがここで失敗しうる。
func buildRule(rc config.CommitIntentRule) (rule, error) {
	r := rule{
		types:      rc.Types,
		typesSet:   toSet(rc.Types),
		scopesSet:  optionalSet(rc.Scopes),
		breaking:   rc.Breaking,
		allow:      rc.Allow,
		require:    rc.Require,
		deny:       rc.Deny,
		denyDiffRe: rc.DenyDiff,
		on:         rc.On,
		reason:     rc.Reason,
	}

	if rc.DenyDiff != "" {
		// 差分は複数行なので、"^"/"$" が行頭・行末に効くよう (?m) を自動で付与する
		// （docsync の when と同じ仕様）。on 指定時は 1 行ずつ照合するため (?m) は
		// 効かないが、on 省略時（複数行に当てる）と正規表現を使い回せるよう付与自体は
		// 変えない（1 行に対する ^/$ の意味は変わらない）。
		re, err := regexp.Compile(`(?m)` + rc.DenyDiff)
		if err != nil {
			return rule{}, fmt.Errorf("commitintent: rules.deny_diff %q のコンパイルに失敗しました: %w", rc.DenyDiff, err)
		}
		r.denyDiff = re
	}

	return r, nil
}

func toSet(items []string) map[string]bool {
	set := make(map[string]bool, len(items))
	for _, it := range items {
		set[it] = true
	}
	return set
}

// optionalSet は「未指定」と「空」を区別する scopesSet 用。空なら nil を返し、
// rule.scopesSet == nil を「scope を問わない」の印として使えるようにする。
func optionalSet(items []string) map[string]bool {
	if len(items) == 0 {
		return nil
	}
	return toSet(items)
}

// Granularity はコミットごとに 1 回ずつ見る。メッセージと差分が 1:1 で対応していないと
// 意味を持たないため squashed は選べない。
func (c *Check) Granularity() check.Granularity {
	return check.GranularityPerCommit
}

// Run は ctx.Message から type/scope/breaking を取り出し、一致するルールの
// allow/require/deny/deny_diff をそれぞれ ctx.Source の変更内容と突き合わせる。
func (c *Check) Run(ctx check.Context) ([]check.Violation, error) {
	subject := commitmsg.FirstLine(ctx.Message)
	if commitmsg.IsAutoGenerated(subject) {
		return nil, nil
	}

	parsed, ok := commitmsg.Parse(subject)
	if !ok {
		// subject の体裁の検証は commit-subject の責務。ここで重ねて報告しない。
		return nil, nil
	}

	changed, deleted, err := changedAndDeleted(ctx.Source)
	if err != nil {
		return nil, err
	}
	if len(changed) == 0 && len(deleted) == 0 {
		return nil, nil
	}

	var violations []check.Violation
	for _, r := range c.rules {
		if !ruleApplies(r, parsed, ctx.Message) {
			continue
		}
		rv, err := evaluateRule(r, ctx.Source, changed, deleted)
		if err != nil {
			return nil, err
		}
		violations = append(violations, rv...)
	}

	return violations, nil
}

func changedAndDeleted(src check.Source) (changed, deleted []string, err error) {
	changed, err = src.ChangedFiles()
	if err != nil {
		return nil, nil, fmt.Errorf("commitintent: 変更ファイルの取得に失敗しました: %w", err)
	}
	deleted, err = src.DeletedFiles()
	if err != nil {
		return nil, nil, fmt.Errorf("commitintent: 削除ファイルの取得に失敗しました: %w", err)
	}
	return changed, deleted, nil
}

// ruleApplies は types/scopes/breaking を見て、このコミットに r を適用するかを決める。
func ruleApplies(r rule, parsed commitmsg.Parsed, message string) bool {
	if !r.typesSet[parsed.Type] {
		return false
	}
	if r.scopesSet != nil && !r.scopesSet[parsed.Scope] {
		return false
	}
	if r.breaking != nil && commitmsg.IsBreaking(message) != *r.breaking {
		return false
	}
	return true
}

// evaluateRule は 1 ルール分の allow/require/deny/deny_diff をそれぞれ評価し、
// 検出した Violation をまとめて返す。
func evaluateRule(r rule, src check.Source, changed, deleted []string) ([]check.Violation, error) {
	var violations []check.Violation

	if v, hit, err := evalAllow(r, changed, deleted); err != nil {
		return nil, err
	} else if hit {
		violations = append(violations, v)
	}

	if v, hit, err := evalRequire(r, changed); err != nil {
		return nil, err
	} else if hit {
		violations = append(violations, v)
	}

	if v, hit, err := evalDeny(r, changed, deleted); err != nil {
		return nil, err
	} else if hit {
		violations = append(violations, v)
	}

	if v, hit, err := evalDenyDiff(r, src, changed, deleted); err != nil {
		return nil, err
	} else if hit {
		violations = append(violations, v)
	}

	return violations, nil
}

// evalAllow は allow を評価する。削除も「このルールが許す範囲を外れた変更」に含める。
// 例えば docs: を名乗ってコードを削除しても、ChangedFiles（ACMR）だけを見ていると
// 素通りしてしまうため。
func evalAllow(r rule, changed, deleted []string) (check.Violation, bool, error) {
	reason := resolveReason(r.reason, fmt.Sprintf("%s は %s だけを変更するはずです", r.label(), strings.Join(r.allow, ", ")))
	return evalFileRule(r.allow, changed, deleted, "allow", true, reason)
}

// evalRequire は require を評価する。require は「変更ファイルの少なくとも 1 つ」を
// 求めるルールなので、削除は満たしたことにしない（意図的）。例えば「テストを消した」
// コミットで require: ['**/*_test.go'] を、消したテストファイル自身で満たせては
// 本末転倒なため、changed（ACMR）だけを見る（deleted は渡さない）。
func evalRequire(r rule, changed []string) (check.Violation, bool, error) {
	if len(r.require) == 0 {
		return check.Violation{}, false, nil
	}
	matched, _, err := matchFiles(r.require, changed, nil)
	if err != nil {
		return check.Violation{}, false, fmt.Errorf("commitintent: rules.require の評価に失敗しました: %w", err)
	}
	if len(matched) > 0 {
		return check.Violation{}, false, nil
	}
	reason := resolveReason(r.reason, fmt.Sprintf("%s は対応する変更を伴うはずです", r.label()))
	// reason を指定していても、何が不足しているか（require のどのパターンに
	// 一致する変更が要るか）が分かるよう、パターンの一覧を必ず添える。
	summary := fmt.Sprintf("%s（次のいずれかに一致する変更が必要: %s）", reason, strings.Join(r.require, ", "))
	return violation(summary, changed), true, nil
}

func evalDeny(r rule, changed, deleted []string) (check.Violation, bool, error) {
	reason := resolveReason(r.reason, fmt.Sprintf("%s は %s を変更してはいけません", r.label(), strings.Join(r.deny, ", ")))
	return evalFileRule(r.deny, changed, deleted, "deny", false, reason)
}

// evalFileRule は allow と deny を共通の形で評価する。patterns が空なら評価自体を
// 省く。invert が true（allow）なら一致しなかったファイル（outliers）を、false
// （deny）なら一致したファイル（hits）を違反として報告する。
func evalFileRule(patterns, changed, deleted []string, errKind string, invert bool, reason string) (check.Violation, bool, error) {
	if len(patterns) == 0 {
		return check.Violation{}, false, nil
	}
	matched, unmatched, err := matchFiles(patterns, changed, deleted)
	if err != nil {
		return check.Violation{}, false, fmt.Errorf("commitintent: rules.%s の評価に失敗しました: %w", errKind, err)
	}
	files := matched
	if invert {
		files = unmatched
	}
	if len(files) == 0 {
		return check.Violation{}, false, nil
	}
	return violation(reason, files), true, nil
}

// evalDenyDiff は deny_diff を評価する。削除も差分を持つ（消えた内容が "-" 行として
// 出る）ため、同じ禁止パターンを削除ファイルの差分にも当てる。「refactor: と称して
// コードごと消す」のような抜け穴を防ぐ。
func evalDenyDiff(r rule, src check.Source, changed, deleted []string) (check.Violation, bool, error) {
	if r.denyDiff == nil {
		return check.Violation{}, false, nil
	}

	hits, err := denyDiffHits(src, r, changed, false)
	if err != nil {
		return check.Violation{}, false, err
	}
	deletedHits, err := denyDiffHits(src, r, deleted, true)
	if err != nil {
		return check.Violation{}, false, err
	}
	hits = append(hits, deletedHits...)

	if len(hits) == 0 {
		return check.Violation{}, false, nil
	}
	reason := resolveReason(r.reason, fmt.Sprintf("%s の差分が禁止パターン %s に一致しています", r.label(), r.denyDiffRe))
	return violation(reason, hits), true, nil
}

// denyDiffHits は files（changed または deleted）の各差分を r.denyDiff に照合する。
// on 省略時は差分テキスト全体に、on 指定時は追加行/削除行それぞれの中身（先頭の +/- を
// 落とし、ヘッダ行も除いたもの）に 1 行ずつ当て、どの行に一致したかがわかるよう
// diffutil.FormatHit で "path:line: text" 形式にする。
func denyDiffHits(src check.Source, r rule, files []string, deleted bool) ([]string, error) {
	var hits []string
	for _, f := range files {
		diff, err := src.DiffLines(f)
		if err != nil {
			return nil, fmt.Errorf("commitintent: %s の差分取得に失敗しました: %w", f, err)
		}

		if r.on == "" {
			if r.denyDiff.MatchString(diff) {
				if deleted {
					hits = append(hits, check.DeletedLabel(f))
				} else {
					hits = append(hits, f)
				}
			}
			continue
		}

		for _, ln := range diffutil.LinesOn(diff, r.on) {
			if r.denyDiff.MatchString(ln.Text) {
				hits = append(hits, diffutil.FormatHit(f, ln.Num, ln.Text))
			}
		}
	}
	return hits, nil
}

// resolveReason は reason が空なら defaultReason を使う。allow/require/deny/deny_diff の
// 4 か所が同じ判定を持つための共通処理。
func resolveReason(reason, defaultReason string) string {
	if reason == "" {
		return defaultReason
	}
	return reason
}

// violation は summary の末尾に ":" を付けて Violation を組み立てる。allow/require/
// deny/deny_diff の 4 か所が同じ形で Violation を作るための共通処理。
func violation(summary string, files []string) check.Violation {
	return check.Violation{Summary: summary + ":", Files: files}
}

// matchFiles は changed と deleted の各ファイルを patterns に照合し、一致したもの
// （matched）と一致しなかったもの（unmatched）に分ける。deleted 側はどちらに転んでも
// check.DeletedLabel を付け、変更されたファイルと見分けが付くようにする。
// deleted は nil でもよい（require のように削除を対象にしないルール向け）。
func matchFiles(patterns, changed, deleted []string) (matched, unmatched []string, err error) {
	for _, f := range changed {
		ok, err := matchesAny(patterns, f)
		if err != nil {
			return nil, nil, err
		}
		if ok {
			matched = append(matched, f)
		} else {
			unmatched = append(unmatched, f)
		}
	}
	for _, f := range deleted {
		ok, err := matchesAny(patterns, f)
		if err != nil {
			return nil, nil, err
		}
		if ok {
			matched = append(matched, check.DeletedLabel(f))
		} else {
			unmatched = append(unmatched, check.DeletedLabel(f))
		}
	}
	return matched, unmatched, nil
}

func matchesAny(patterns []string, f string) (bool, error) {
	for _, pat := range patterns {
		ok, err := doublestar.Match(pat, f)
		if err != nil {
			return false, fmt.Errorf("パターン %q が不正です: %w", pat, err)
		}
		if ok {
			return true, nil
		}
	}
	return false, nil
}
