// Package commitintent はコミットメッセージの type/scope と、実際の変更内容（差分）の
// 整合を検査する。commit-subject が subject の体裁だけを見るのに対し、こちらは
// 「docs: と名乗りながらコードを書き換えている」のような、申告と実態の乖離を検知する。
package commitintent

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/bmatcuk/doublestar/v4"

	"github.com/fuchigta/spotter/internal/check"
	"github.com/fuchigta/spotter/internal/commitmsg"
	"github.com/fuchigta/spotter/internal/config"
)

type rule struct {
	types      []string
	typesSet   map[string]bool
	scopesSet  map[string]bool
	allow      []string
	require    []string
	denyDiff   *regexp.Regexp
	denyDiffRe string
	reason     string
}

func (r rule) label() string {
	return strings.Join(r.types, "/")
}

// Check は commit-intent 検査の 1 インスタンス。
type Check struct {
	rules []rule
}

// New は config.CheckConfig から Check を組み立てる。rules の各項目はここで検証し、
// 不正な設定は起動時に検出する。
func New(cc config.CheckConfig) (*Check, error) {
	if len(cc.Rules) == 0 {
		return nil, fmt.Errorf("commitintent: rules には少なくとも 1 件のルールが必要です")
	}

	c := &Check{}
	for _, rc := range cc.Rules {
		if len(rc.Types) == 0 {
			return nil, fmt.Errorf("commitintent: rules には types が必要です")
		}
		for _, t := range rc.Types {
			if t == "" {
				return nil, fmt.Errorf("commitintent: rules.types に空文字は指定できません")
			}
		}
		if len(rc.Allow) == 0 && len(rc.Require) == 0 && rc.DenyDiff == "" {
			return nil, fmt.Errorf("commitintent: rules には allow / require / deny_diff のいずれか 1 つが必要です")
		}

		typesSet := make(map[string]bool, len(rc.Types))
		for _, t := range rc.Types {
			typesSet[t] = true
		}

		var scopesSet map[string]bool
		if len(rc.Scopes) > 0 {
			scopesSet = make(map[string]bool, len(rc.Scopes))
			for _, s := range rc.Scopes {
				if s == "" {
					return nil, fmt.Errorf("commitintent: rules.scopes に空文字は指定できません")
				}
				scopesSet[s] = true
			}
		}

		for _, p := range rc.Allow {
			if !doublestar.ValidatePattern(p) {
				return nil, fmt.Errorf("commitintent: rules.allow: パターン %q が不正です", p)
			}
		}
		for _, p := range rc.Require {
			if !doublestar.ValidatePattern(p) {
				return nil, fmt.Errorf("commitintent: rules.require: パターン %q が不正です", p)
			}
		}

		r := rule{
			types:      rc.Types,
			typesSet:   typesSet,
			scopesSet:  scopesSet,
			allow:      rc.Allow,
			require:    rc.Require,
			denyDiffRe: rc.DenyDiff,
			reason:     rc.Reason,
		}

		if rc.DenyDiff != "" {
			// 差分は複数行なので、"^"/"$" が行頭・行末に効くよう (?m) を自動で付与する
			// （docsync の when と同じ仕様）。
			re, err := regexp.Compile(`(?m)` + rc.DenyDiff)
			if err != nil {
				return nil, fmt.Errorf("commitintent: rules.deny_diff %q のコンパイルに失敗しました: %w", rc.DenyDiff, err)
			}
			r.denyDiff = re
		}

		c.rules = append(c.rules, r)
	}
	return c, nil
}

// Granularity はコミットごとに 1 回ずつ見る。メッセージと差分が 1:1 で対応していないと
// 意味を持たないため squashed は選べない。checks 側からは上書きできない。
func (c *Check) Granularity() check.Granularity {
	return check.GranularityPerCommit
}

// Run は ctx.Message から type/scope を取り出し、一致するルールの allow/require/deny_diff
// をそれぞれ ctx.Source の変更内容と突き合わせる。
func (c *Check) Run(ctx check.Context) ([]check.Violation, error) {
	subject := commitmsg.FirstLine(ctx.Message)
	if commitmsg.IsAutoGenerated(subject) {
		return nil, nil
	}

	parsed, ok := commitmsg.Parse(subject)
	if !ok {
		// subject の体裁の検証は commit-subject の責務。ここで重ねて報告しない。
		return nil, nil
	}

	src := ctx.Source
	changed, err := src.ChangedFiles()
	if err != nil {
		return nil, fmt.Errorf("commitintent: 変更ファイルの取得に失敗しました: %w", err)
	}
	if len(changed) == 0 {
		return nil, nil
	}

	var violations []check.Violation
	for _, r := range c.rules {
		if !r.typesSet[parsed.Type] {
			continue
		}
		if r.scopesSet != nil && !r.scopesSet[parsed.Scope] {
			continue
		}

		if len(r.allow) > 0 {
			var outliers []string
			for _, f := range changed {
				matched, err := matchesAny(r.allow, f)
				if err != nil {
					return nil, fmt.Errorf("commitintent: rules.allow の評価に失敗しました: %w", err)
				}
				if !matched {
					outliers = append(outliers, f)
				}
			}
			if len(outliers) > 0 {
				reason := r.reason
				if reason == "" {
					reason = fmt.Sprintf("%s は %s だけを変更するはずです", r.label(), strings.Join(r.allow, ", "))
				}
				violations = append(violations, check.Violation{Summary: reason + ":", Files: outliers})
			}
		}

		if len(r.require) > 0 {
			satisfied := false
			for _, f := range changed {
				matched, err := matchesAny(r.require, f)
				if err != nil {
					return nil, fmt.Errorf("commitintent: rules.require の評価に失敗しました: %w", err)
				}
				if matched {
					satisfied = true
					break
				}
			}
			if !satisfied {
				reason := r.reason
				if reason == "" {
					reason = fmt.Sprintf("%s は %s のいずれかを伴うはずです", r.label(), strings.Join(r.require, ", "))
				}
				violations = append(violations, check.Violation{Summary: reason + ":", Files: changed})
			}
		}

		if r.denyDiff != nil {
			var hits []string
			for _, f := range changed {
				diff, err := src.DiffLines(f)
				if err != nil {
					return nil, fmt.Errorf("commitintent: %s の差分取得に失敗しました: %w", f, err)
				}
				if r.denyDiff.MatchString(diff) {
					hits = append(hits, f)
				}
			}
			if len(hits) > 0 {
				reason := r.reason
				if reason == "" {
					reason = fmt.Sprintf("%s の差分が禁止パターン %s に一致しています", r.label(), r.denyDiffRe)
				}
				violations = append(violations, check.Violation{Summary: reason + ":", Files: hits})
			}
		}
	}

	return violations, nil
}

func matchesAny(patterns []string, f string) (bool, error) {
	for _, pat := range patterns {
		ok, err := doublestar.Match(pat, f)
		if err != nil {
			return false, err
		}
		if ok {
			return true, nil
		}
	}
	return false, nil
}
