package commitmsg_test

import (
	"testing"

	"github.com/fuchigta/spotter/internal/commitmsg"
)

func TestFirstLine(t *testing.T) {
	tests := []struct {
		msg  string
		want string
	}{
		{"feat: 追加する", "feat: 追加する"},
		{"feat: 追加する\n\n詳細な本文", "feat: 追加する"},
		{"feat: 追加する\r\n\r\n詳細な本文", "feat: 追加する"},
		{"", ""},
	}
	for _, tt := range tests {
		if got := commitmsg.FirstLine(tt.msg); got != tt.want {
			t.Errorf("FirstLine(%q) = %q, want %q", tt.msg, got, tt.want)
		}
	}
}

func TestIsAutoGenerated(t *testing.T) {
	tests := []struct {
		subject string
		want    bool
	}{
		{"", true},
		{"Merge branch 'main' into feature", true},
		{"Revert \"feat: 何か\"", true},
		{"feat: 追加する", false},
	}
	for _, tt := range tests {
		if got := commitmsg.IsAutoGenerated(tt.subject); got != tt.want {
			t.Errorf("IsAutoGenerated(%q) = %v, want %v", tt.subject, got, tt.want)
		}
	}
}

func TestParse(t *testing.T) {
	tests := []struct {
		name    string
		subject string
		wantOK  bool
		want    commitmsg.Parsed
	}{
		{"通常の feat", "feat: 新機能を追加する", true, commitmsg.Parsed{Type: "feat", Description: "新機能を追加する"}},
		{"scope つき", "fix(rollup): 直す", true, commitmsg.Parsed{Type: "fix", Scope: "rollup", Description: "直す"}},
		{"破壊的変更", "feat(judge)!: 列挙値を変える", true, commitmsg.Parsed{Type: "feat", Scope: "judge", Breaking: true, Description: "列挙値を変える"}},
		{"未知の type でも一般形なら parse できる", "wip: 作業中", true, commitmsg.Parsed{Type: "wip", Description: "作業中"}},
		{"コロンの後にスペースが無い", "feat:追加する", false, commitmsg.Parsed{}},
		{"説明が無い", "feat: ", false, commitmsg.Parsed{}},
		{"コロンが無い", "適当な文章", false, commitmsg.Parsed{}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := commitmsg.Parse(tt.subject)
			if ok != tt.wantOK {
				t.Fatalf("Parse(%q) ok = %v, want %v", tt.subject, ok, tt.wantOK)
			}
			if !ok {
				return
			}
			if got != tt.want {
				t.Errorf("Parse(%q) = %+v, want %+v", tt.subject, got, tt.want)
			}
		})
	}
}

func TestIsBreaking(t *testing.T) {
	tests := []struct {
		name string
		msg  string
		want bool
	}{
		{"subject の !", "feat(judge)!: 列挙値を変える", true},
		{"scope 無しの !", "feat!: 列挙値を変える", true},
		{"BREAKING CHANGE フッタ", "feat: 新機能\n\n詳細な本文\n\nBREAKING CHANGE: 設定キーの意味が変わる", true},
		{"BREAKING-CHANGE フッタ（ハイフン）", "fix: 直す\n\nBREAKING-CHANGE: 挙動が変わる", true},
		{"! とフッタの両方", "feat!: 変える\n\nBREAKING CHANGE: 挙動が変わる", true},
		{"通常の feat", "feat: 新機能を追加する", false},
		{"本文中に BREAKING を含むが行頭ではない", "feat: 新機能\n\n詳細（BREAKING CHANGE: は含まない）", false},
		{"パース不能な subject でもフッタがあれば true", "適当な文章\n\nBREAKING CHANGE: 挙動が変わる", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := commitmsg.IsBreaking(tt.msg); got != tt.want {
				t.Errorf("IsBreaking(%q) = %v, want %v", tt.msg, got, tt.want)
			}
		})
	}
}
