// Package commitmsg は Conventional Commits 形式のコミットメッセージを解析する。
//
// commit-subject（体裁の検証）と commit-intent（メッセージと差分の整合の検証）は
// どちらも subject から type/scope を取り出す必要があるため、二重管理を避けるために
// ここへ切り出す。allowed_types のような「どの type を許可するか」の判断はここでは持たず、
// 呼び出し側（各検査）の責務にする。
package commitmsg

import (
	"regexp"
	"strings"
)

// Parsed は Conventional Commits の subject をパートに分解したもの。
type Parsed struct {
	Type        string
	Scope       string
	Breaking    bool
	Description string
}

// subjectPattern は "<type>(<scope>)!: <description>" の一般形。scope は任意、
// ! は破壊的変更、コロンの後に半角スペース 1 つを挟んで説明が続く。
var subjectPattern = regexp.MustCompile(`^([a-zA-Z0-9_-]+)(\(([a-zA-Z0-9._/-]+)\))?(!)?: (.+)$`)

// FirstLine はコミットメッセージの 1 行目（subject）を返す。
func FirstLine(msg string) string {
	if i := strings.IndexByte(msg, '\n'); i >= 0 {
		return strings.TrimRight(msg[:i], "\r")
	}
	return strings.TrimRight(msg, "\r")
}

// IsAutoGenerated は subject が git 自身の生成物（`git revert`）か、空かどうかを返す。
// これらは Conventional Commits の検証対象外にする（commit-subject と同じ扱い）。
//
// マージコミットはここでは判定しない。マージコミット自体は range モードの
// RevListNoMerges と staged モードの Repo.InMerge（internal/cli/check.go）で
// 既に検査対象から外れているため、「subject が "Merge " で始まる」というだけで
// 判定すると、"Merge stuff" のような普通のコミットが commit-subject・commit-intent
// の両方をすり抜けてしまう抜け穴になる。
//
// `git revert` が生成する subject は常に `Revert "<元の subject>"`（ダブルクォート
// 付き）という決まった形なので、それだけを対象にする。"Revert stuff" のような
// 普通の subject は対象にしない。
func IsAutoGenerated(subject string) bool {
	return subject == "" || strings.HasPrefix(subject, `Revert "`)
}

// Parse は subject が Conventional Commits の一般形に合うかを調べ、合えば type/scope/
// breaking/description に分解する。ok が false なら subject はこの形になっていない
// （どの type が許可されているかとは無関係。それは呼び出し側で判定する）。
func Parse(subject string) (Parsed, bool) {
	m := subjectPattern.FindStringSubmatch(subject)
	if m == nil {
		return Parsed{}, false
	}
	return Parsed{
		Type:        m[1],
		Scope:       m[3],
		Breaking:    m[4] == "!",
		Description: m[5],
	}, true
}

// breakingFooterPattern は本文フッタの破壊的変更トレーラ。Conventional Commits の仕様上、
// トークンは大文字の "BREAKING CHANGE" または "BREAKING-CHANGE" と決まっている。
var breakingFooterPattern = regexp.MustCompile(`(?m)^BREAKING[ -]CHANGE:`)

// IsBreaking はコミットメッセージ全体（subject + 本文）が Conventional Commits の
// 破壊的変更を表しているかどうかを返す。subject の "!"（例: "feat(api)!: ..."）と、
// 本文フッタの "BREAKING CHANGE:" / "BREAKING-CHANGE:" のどちらかがあれば true。
// subject が一般形に合わない場合は "!" 側を判定できないため、フッタだけで判断する。
func IsBreaking(msg string) bool {
	if parsed, ok := Parse(FirstLine(msg)); ok && parsed.Breaking {
		return true
	}
	return breakingFooterPattern.MatchString(msg)
}
