// Package commitsubject は Conventional Commits の subject 行を検証する検査を実装する。
package commitsubject

import (
	"fmt"

	"github.com/fuchigta/spotter/internal/check"
	"github.com/fuchigta/spotter/internal/commitmsg"
	"github.com/fuchigta/spotter/internal/config"
)

// Check は commit-subject 検査の 1 インスタンス。
type Check struct {
	allowedTypes map[string]bool
}

// New は config.CheckConfig から Check を組み立てる。allowed_types は必須で、
// 空だと「常に不一致」という無意味な検査になってしまうため起動時に拒否する。
func New(cc config.CheckConfig) (*Check, error) {
	if len(cc.AllowedTypes) == 0 {
		return nil, fmt.Errorf("commitsubject: allowed_types が空です")
	}

	allowed := make(map[string]bool, len(cc.AllowedTypes))
	for _, t := range cc.AllowedTypes {
		if t == "" {
			return nil, fmt.Errorf("commitsubject: allowed_types に空文字は指定できません")
		}
		allowed[t] = true
	}

	return &Check{allowedTypes: allowed}, nil
}

// Granularity はコミットごとに 1 回ずつ見る。commit-subject の免除は既定で無効
// （config.ResolveExempt の DefaultExemptEnable を参照）。
func (c *Check) Granularity() check.Granularity {
	return check.GranularityPerCommit
}

// Run は ctx.Message の 1 行目（subject）が Conventional Commits の形式に合い、かつ
// type が allowed_types に含まれるかを検証する。
func (c *Check) Run(ctx check.Context) ([]check.Violation, error) {
	subject := commitmsg.FirstLine(ctx.Message)

	// git が自動生成するマージ・リバートのメッセージは対象外にする。
	if commitmsg.IsAutoGenerated(subject) {
		return nil, nil
	}

	parsed, ok := commitmsg.Parse(subject)
	if ok && c.allowedTypes[parsed.Type] {
		return nil, nil
	}

	return []check.Violation{{Summary: fmt.Sprintf("不正なコミットメッセージです: %s", subject)}}, nil
}
